---
functional:
  - Пользователь должен иметь возможность зарегестрирваться
  - На сайте должна быть возможность просматривать и выбирать следующее рейтинг, игра с ботом, игра с другом по ссылке
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность создавать свою игру
  - Пользователь должен иметь возможность выбрать подходящий язык кодирования
  - Пользователь должен иметь возможность создавать игру и участвовать свободно в других, а так же иметь возможность пользоваться игровым функционалом
  - Сайт должен корректно обрабатывать и загружать игровые процессы 
  - Пользователь должен иметь возможность подключиться к игре, пока она не закончена, если вдруг по каким либо причинам он вылетел
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть удобен как для новичка, так и для опытного програмиста
  - Пользователь должен иметь возможность просматривать рейтинг других игроков
